### ISSUE TITLE
大图页面崩溃

### ISSUE THREAD

**Issue by hancongAndroid** [githubwing/DragPhotoView#2]
在大图页面返回的缩放,移动后,界面崩溃
`12-27 16:39:47.441 22533-22533/com.wingsofts.myapplication E/MotionEvent-JNI: An exception occurred: pointerCount 1, pointerIndex -1.
12-27 16:39:47.441 22533-22533/com.wingsofts.myapplication E/InputEventReceiver: Exception dispatching input event.
12-27 16:39:47.441 22533-22533/com.wingsofts.myapplication E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
12-27 16:39:47.451 22533-22533/com.wingsofts.myapplication E/MessageQueue-JNI: java.lang.IllegalArgumentException: pointerIndex out of range
                                                                                   at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                                   at android.view.MotionEvent.getX(MotionEvent.java:2286)
                                                                                   at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2096)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
                                                                                   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
                                                                                   at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
                                                                                   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
                                                                                   at android.view.View.dispatchPointerEvent(View.java:10228)
                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5344)
                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5180)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
                                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
                                                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4781)
                                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
                                                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4838)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
                                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
                                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7306)
                                                                                   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7184)
                                                                                   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7145)
                                                                                   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7416)
                                                                                   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                   at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                   at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                   at android.os.Looper.loop(Looper.java:143)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by githubwing** [comment]
参考demo  重写viewpager的onInterceptTouchEvent

**Comment by hancongAndroid** [comment]
说出来你可能不信，就是运行你的demo崩溃的

**Comment by githubwing** [comment]
是最新代码吗
